import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Udo social",
  description: "Generated by create next app",
  
  openGraph: {
    title: 'UDO Socials',
    description: 'Únete a la comunidad tecnológica de la UDO Monagas.',
    url: 'https://udo-social.vercel.app',
    siteName: 'UDO Social',
    images: [
      {
        url: 'https://udo-social.vercel.app/og-image.png', // Ruta absoluta
        width: 1200,
        height: 630,
        alt: 'Previsualización de UDO Social',
      },
    ],
    locale: 'es_VE',
    type: 'website',
  },
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
